import type {
  FragmentQuality,
  FragmentElement,
  FragmentForm,
  FragmentMechanism,
} from '../types/fragment';

export interface FragmentEntry {
  id: string;
  name: string;
  quality: FragmentQuality;
  type: 'element' | 'form' | 'mechanism';
  subType: string;
  carryingCapacity: number;
  description: string;
  rarity: number;
}

export const FRAGMENTS: {
  quality: FragmentEntry[];
  element: FragmentEntry[];
  form: FragmentEntry[];
  mechanism: FragmentEntry[];
} = {
  quality: [
    {
      id: 'frag_iron_word',
      name: '铁言',
      quality: 'iron_word',
      type: 'element',
      subType: 'iron_word',
      carryingCapacity: 3,
      description: '基础碎片，承载简单的文字力量',
      rarity: 1,
    },
    {
      id: 'frag_steel_word',
      name: '钢言',
      quality: 'steel_word',
      type: 'element',
      subType: 'steel_word',
      carryingCapacity: 5,
      description: '经过锤炼的文字，蕴含更强的力量',
      rarity: 2,
    },
    {
      id: 'frag_silver_sentence',
      name: '银句',
      quality: 'silver_sentence',
      type: 'element',
      subType: 'silver_sentence',
      carryingCapacity: 8,
      description: '闪耀着银光的句子，具有非凡的力量',
      rarity: 3,
    },
    {
      id: 'frag_source_chapter',
      name: '源章',
      quality: 'source_chapter',
      type: 'element',
      subType: 'source_chapter',
      carryingCapacity: 12,
      description: '源自古籍的篇章，承载深厚的智慧',
      rarity: 4,
    },
    {
      id: 'frag_divine_codex',
      name: '神典',
      quality: 'divine_codex',
      type: 'element',
      subType: 'divine_codex',
      carryingCapacity: 20,
      description: '传说级碎片，蕴含神明般的文字力量',
      rarity: 5,
    },
  ],
  element: [
    {
      id: 'elem_fire',
      name: '炎',
      quality: 'steel_word',
      type: 'element',
      subType: 'fire',
      carryingCapacity: 5,
      description: '火焰元素，象征热情与毁灭',
      rarity: 2,
    },
    {
      id: 'elem_ice',
      name: '冰',
      quality: 'steel_word',
      type: 'element',
      subType: 'ice',
      carryingCapacity: 5,
      description: '寒冰元素，象征宁静与冻结',
      rarity: 2,
    },
    {
      id: 'elem_thunder',
      name: '雷',
      quality: 'silver_sentence',
      type: 'element',
      subType: 'thunder',
      carryingCapacity: 8,
      description: '雷电元素，象征速度与冲击',
      rarity: 3,
    },
    {
      id: 'elem_light',
      name: '光',
      quality: 'silver_sentence',
      type: 'element',
      subType: 'light',
      carryingCapacity: 8,
      description: '光明元素，象征净化与守护',
      rarity: 3,
    },
    {
      id: 'elem_shadow',
      name: '影',
      quality: 'silver_sentence',
      type: 'element',
      subType: 'shadow',
      carryingCapacity: 8,
      description: '暗影元素，象征隐秘与诡变',
      rarity: 3,
    },
    {
      id: 'elem_earth',
      name: '地',
      quality: 'steel_word',
      type: 'element',
      subType: 'earth',
      carryingCapacity: 5,
      description: '大地元素，象征稳固与厚重',
      rarity: 2,
    },
    {
      id: 'elem_wind',
      name: '风',
      quality: 'steel_word',
      type: 'element',
      subType: 'wind',
      carryingCapacity: 5,
      description: '风之元素，象征自由与变幻',
      rarity: 2,
    },
  ],
  form: [
    {
      id: 'form_single',
      name: '单体',
      quality: 'iron_word',
      type: 'form',
      subType: 'single',
      carryingCapacity: 3,
      description: '对单个目标发动攻击',
      rarity: 1,
    },
    {
      id: 'form_aoe',
      name: '范围',
      quality: 'steel_word',
      type: 'form',
      subType: 'aoe',
      carryingCapacity: 5,
      description: '对范围内所有目标发动攻击',
      rarity: 2,
    },
    {
      id: 'form_chain',
      name: '连锁',
      quality: 'silver_sentence',
      type: 'form',
      subType: 'chain',
      carryingCapacity: 8,
      description: '在目标之间连锁传递攻击',
      rarity: 3,
    },
    {
      id: 'form_projectile',
      name: '投射',
      quality: 'iron_word',
      type: 'form',
      subType: 'projectile',
      carryingCapacity: 3,
      description: '远程投射攻击',
      rarity: 1,
    },
    {
      id: 'form_field',
      name: '领域',
      quality: 'source_chapter',
      type: 'form',
      subType: 'field',
      carryingCapacity: 12,
      description: '在区域内创造持续效果的领域',
      rarity: 4,
    },
    {
      id: 'form_summon',
      name: '召唤',
      quality: 'source_chapter',
      type: 'form',
      subType: 'summon',
      carryingCapacity: 12,
      description: '召唤实体协助战斗',
      rarity: 4,
    },
  ],
  mechanism: [
    {
      id: 'mech_life_steal',
      name: '汲取',
      quality: 'steel_word',
      type: 'mechanism',
      subType: 'life_steal',
      carryingCapacity: 5,
      description: '将部分伤害转化为生命恢复',
      rarity: 2,
    },
    {
      id: 'mech_shield',
      name: '护盾',
      quality: 'steel_word',
      type: 'mechanism',
      subType: 'shield',
      carryingCapacity: 5,
      description: '生成护盾吸收伤害',
      rarity: 2,
    },
    {
      id: 'mech_purify',
      name: '净化',
      quality: 'silver_sentence',
      type: 'mechanism',
      subType: 'purify',
      carryingCapacity: 8,
      description: '移除负面状态和效果',
      rarity: 3,
    },
    {
      id: 'mech_resonance',
      name: '共鸣',
      quality: 'source_chapter',
      type: 'mechanism',
      subType: 'resonance',
      carryingCapacity: 12,
      description: '与已有技能产生共鸣，增强效果',
      rarity: 4,
    },
    {
      id: 'mech_overload',
      name: '过载',
      quality: 'silver_sentence',
      type: 'mechanism',
      subType: 'overload',
      carryingCapacity: 8,
      description: '以额外消耗为代价大幅提升威力',
      rarity: 3,
    },
    {
      id: 'mech_echo',
      name: '回响',
      quality: 'divine_codex',
      type: 'mechanism',
      subType: 'echo',
      carryingCapacity: 20,
      description: '技能释放后额外触发一次效果',
      rarity: 5,
    },
  ],
};